import React, { useState } from 'react';
import { Check, Copy, FileText, Printer, X } from 'lucide-react';
import { CivicIncident } from '../types';
import { Language, translations } from '../i18n/translations';

interface CivicReportModalProps {
  incident: CivicIncident;
  language: Language;
  onClose: () => void;
}

export const CivicReportModal: React.FC<CivicReportModalProps> = ({
  incident,
  language,
  onClose,
}) => {
  const [copied, setCopied] = useState(false);
  const t = translations[language].reportGen;

  const formattedDate = new Date(incident.timestamp).toLocaleString(
    language === 'bn' ? 'bn-BD' : 'en-US',
    {
      dateStyle: 'full',
      timeStyle: 'medium',
    }
  );

  const rawReportText = `===========================================================
${t.officialTitle}
${t.subtitle}
===========================================================

${t.incidentRef}: ${incident.id}
${t.timestamp}: ${formattedDate}
${t.location}: ${incident.locationName}, ${incident.roadName}, ${incident.city}
Coordinates: [${incident.latitude.toFixed(5)}, ${incident.longitude.toFixed(5)}]

${t.severityScore}: ${incident.severity} / 100 (${incident.priority} PRIORITY)
Suggested Service: ${incident.suggestedServiceCategory}

${t.observedDefect}:
${incident.description}
${incident.estimatedDepthCm ? `Estimated Physical Dimension: ~${incident.estimatedDepthCm} cm depth/extent` : ''}

${t.civicImpact}:
${incident.civicImpactChain.impact}
Nearby Facilities Exposed: ${incident.nearbyFacilities.map((f) => `${f.name} (${f.distanceMeters}m)`).join(', ') || 'None within 500m'}

${t.recommendedAction}:
${incident.recommendedAction}

EVIDENCE:
Field image attached with AI verification bounding overlays (Confidence: ${(incident.confidence * 100).toFixed(0)}%).
Status: ${incident.status}

Generated by NAGAR-EYE Civic Infrastructure Intelligence Platform
===========================================================`;

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(rawReportText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // Fallback
    }
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/70 backdrop-blur-xs p-3 sm:p-4 overflow-y-auto">
      <div className="relative w-full max-w-2xl rounded-2xl bg-white shadow-2xl border border-slate-200 overflow-hidden my-auto animate-fadeIn">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 bg-slate-900 text-white">
          <div className="flex items-center gap-2.5">
            <div className="p-2 rounded-lg bg-teal-500/20 text-teal-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h2 className="text-sm font-bold tracking-wide">{t.officialTitle}</h2>
              <p className="text-[11px] text-slate-400">{t.subtitle}</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Report Content Body (Printable) */}
        <div className="p-6 space-y-5 text-slate-800 text-xs sm:text-sm max-h-[70vh] overflow-y-auto bg-slate-50/50">
          {/* Metadata Card */}
          <div className="p-4 rounded-xl bg-white border border-slate-200 grid grid-cols-2 sm:grid-cols-4 gap-3">
            <div>
              <span className="text-[10px] uppercase font-bold text-slate-600 block">{t.incidentRef}</span>
              <span className="font-mono font-semibold text-slate-900 text-xs">{incident.id}</span>
            </div>
            <div>
              <span className="text-[10px] uppercase font-bold text-slate-600 block">{t.severityScore}</span>
              <span className="font-bold text-rose-600 text-xs">{incident.severity}/100 • {incident.priority}</span>
            </div>
            <div>
              <span className="text-[10px] uppercase font-bold text-slate-600 block">Status</span>
              <span className="font-semibold text-slate-800 text-xs">{incident.status}</span>
            </div>
            <div>
              <span className="text-[10px] uppercase font-bold text-slate-600 block">Aggregated Reports</span>
              <span className="font-semibold text-slate-800 text-xs">{incident.reportCount} reports</span>
            </div>
          </div>

          {/* Location & Routing */}
          <div className="p-4 rounded-xl bg-white border border-slate-200 space-y-2">
            <div>
              <span className="text-[10px] uppercase font-bold text-slate-600 block">{t.location}</span>
              <p className="font-medium text-slate-900 text-xs sm:text-sm mt-0.5">
                {incident.locationName}, {incident.roadName} (GPS: {incident.latitude.toFixed(4)}, {incident.longitude.toFixed(4)})
              </p>
            </div>
            <div>
              <span className="text-[10px] uppercase font-bold text-slate-600 block">{t.serviceCategory}</span>
              <p className="font-semibold text-teal-800 text-xs sm:text-sm mt-0.5">
                {incident.suggestedServiceCategory}
              </p>
            </div>
          </div>

          {/* Engineering Observation & Impact */}
          <div className="p-4 rounded-xl bg-white border border-slate-200 space-y-3">
            <div>
              <span className="text-[10px] uppercase font-bold text-slate-600 block">{t.observedDefect}</span>
              <p className="text-slate-800 mt-1 leading-relaxed">{incident.description}</p>
              {incident.estimatedDepthCm && (
                <span className="inline-block mt-1 text-xs font-semibold px-2 py-0.5 rounded bg-slate-100 text-slate-700">
                  Estimated Depth / Cavity: ~{incident.estimatedDepthCm} cm
                </span>
              )}
            </div>

            <div>
              <span className="text-[10px] uppercase font-bold text-slate-600 block">{t.civicImpact}</span>
              <p className="text-slate-800 mt-1 leading-relaxed">{incident.civicImpactChain.impact}</p>
              <div className="mt-1 flex flex-wrap gap-1.5">
                {incident.nearbyFacilities.map((fac, idx) => (
                  <span
                    key={idx}
                    className="text-[11px] px-2 py-0.5 rounded-md bg-amber-50 text-amber-900 border border-amber-200"
                  >
                    {fac.name} ({fac.distanceMeters}m)
                  </span>
                ))}
              </div>
            </div>

            <div>
              <span className="text-[10px] uppercase font-bold text-slate-600 block">{t.recommendedAction}</span>
              <p className="text-slate-900 font-medium mt-1 leading-relaxed bg-teal-50/70 p-2.5 rounded-lg border border-teal-200/80">
                {incident.recommendedAction}
              </p>
            </div>
          </div>

          {/* Visual Evidence Preview */}
          <div className="p-4 rounded-xl bg-white border border-slate-200">
            <span className="text-[10px] uppercase font-bold text-slate-600 block mb-2">Verified Visual Evidence</span>
            <div className="w-full h-40 sm:h-48 rounded-lg overflow-hidden border border-slate-200 bg-slate-900">
              <img
                src={incident.imageUrl}
                alt="Civic evidence"
                className="w-full h-full object-cover"
              />
            </div>
            <p className="mt-2 text-[11px] text-slate-600">
              Analyzed via Multi-modal AI Perception Model. Geometric defect bounding validated (Confidence: {(incident.confidence * 100).toFixed(0)}%).
            </p>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="flex items-center justify-between px-6 py-4 bg-white border-t border-slate-200">
          <button
            onClick={onClose}
            className="px-4 py-2 text-xs font-semibold text-slate-600 hover:text-slate-900 hover:bg-slate-100 rounded-lg transition"
          >
            {t.close}
          </button>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className="inline-flex items-center gap-1.5 px-3.5 py-2 text-xs font-semibold rounded-lg border border-slate-300 text-slate-700 bg-white hover:bg-slate-50 transition active:scale-95"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-600" /> : <Copy className="w-4 h-4 text-slate-500" />}
              <span>{copied ? t.copied : t.copyReport}</span>
            </button>

            <button
              onClick={handlePrint}
              className="inline-flex items-center gap-1.5 px-4 py-2 text-xs font-semibold rounded-lg text-white bg-slate-900 hover:bg-slate-800 transition active:scale-95 shadow-sm"
            >
              <Printer className="w-4 h-4" />
              <span>{t.downloadReport}</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
